from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import os
import yaml

ROOT = Path(__file__).resolve().parents[2]


def _bool(value: object, default: bool = False) -> bool:
    if value is None:
        value = default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


@dataclass
class Settings:
    exchange: str = "binance"
    cache_dir: str = "data"
    log_level: str = "INFO"
    timezone: str = "UTC"
    symbol: str = "BTC/USDT"
    timeframe: str = "15m"
    research_timeframe: str = "15m"
    broad_timeframe: str = "1d"
    lookback_bars: int = 30000
    horizon_bars: int = 8
    min_train_rows: int = 1500
    retrain_every_bars: int = 96
    probability_threshold: float = 0.57
    min_expected_return: float = 0.0015
    min_edge_after_cost_bps: float = 5.0
    decision_threshold: float = 0.16
    meta_threshold: float = 0.53
    pt_atr: float = 1.6
    sl_atr: float = 1.0
    memory_k: int = 32
    memory_information_weighted: bool = False
    max_holding_bars: int = 8
    trade_window_enabled: bool = True
    trade_window_required_for_signal: bool = True
    trade_window_min_confidence: float = 0.80
    trade_window_min_expected_return: float = 0.0015
    trade_window_require_base_agreement: bool = True
    trade_window_min_hours: float = 3.0
    trade_window_max_hours: float = 24.0
    trade_window_preferred_min_hours: float = 3.0
    trade_window_preferred_max_hours: float = 4.0
    trade_window_preference_weight: float = 0.10
    trade_window_pt_atr: float = 1.25
    trade_window_sl_atr: float = 0.90
    trade_window_min_net_return: float = 0.0005
    trade_window_target_precision: float = 0.80
    trade_window_min_oos_trades: int = 25
    trade_window_min_holdout_trades: int = 12
    trade_window_min_holdout_wilson: float = 0.60
    trade_window_min_oos_wilson: float = 0.60
    trade_window_require_positive_holdout_backtest: bool = True
    base_require_positive_holdout_return: bool = True
    base_min_holdout_trades: int = 20
    base_min_holdout_profit_factor: float = 1.0
    base_max_holdout_drawdown: float = -0.25
    base_min_holdout_utility: float = 0.0
    require_deployment_manifest_for_signal: bool = True
    trade_window_min_holdout_utility: float = 0.0
    live_max_data_age_minutes: float = 30.0
    trade_window_max_holdout_drawdown: float = -0.25
    trade_window_holdout_frac: float = 0.15
    trade_window_model_path: str = "models/champion/trade_window_specialist.joblib"
    trade_window_xgb_estimators: int = 180
    trade_window_lgbm_estimators: int = 180
    trade_window_hist_max_iter: int = 220
    initial_cash: float = 10000.0
    risk_per_trade: float = 0.005
    max_position_pct: float = 0.25
    max_daily_loss_pct: float = 0.02
    stop_atr_mult: float = 1.0
    take_profit_rr: float = 1.6
    fee_bps: float = 7.0
    slippage_bps: float = 5.0
    impact_bps_per_sqrt: float = 1.5
    max_participation_pct: float = 0.10
    paper_only: bool = True
    sandbox: bool = True
    poll_seconds: int = 60
    live_lookback_bars: int = 1200
    # 0 means scan every discovered active market with a compatible local model.
    live_max_symbols: int = 0
    live_market_types: tuple[str, ...] = ("spot", "swap", "future", "margin", "option")
    live_default_refresh_seconds: int = 60
    # Bounded I/O concurrency for full-universe live assessments.
    live_scan_workers: int = 6
    seed: int = 42
    walk_forward_train_bars: int = 3000
    walk_forward_test_bars: int = 500
    walk_forward_step: int = 250
    validation_purge_bars: int = 12
    population_size: int = 500
    generations: int = 30
    min_trades_promotion: int = 20
    max_promotion_drawdown: float = -0.20
    autonomous_enabled: bool = True
    autonomous_query: str = "latest Bitcoin crypto markets macro catalysts regulation ETF flows volatility"
    autonomous_interval_seconds: int = 900
    intelligence_db: str = "data/intelligence.sqlite"
    memory_db: str = "data/memory.sqlite"
    external_deep_search: bool = True
    external_providers: tuple[str, ...] = ("exa", "tavily")
    external_search_ttl_seconds: int = 1800
    fred_series: tuple[str, ...] = ("DFF", "DGS10", "DTWEXBGS", "VIXCLS")
    sec_ciks: tuple[str, ...] = ()
    growth_enabled: bool = True
    growth_min_folds: int = 4
    growth_min_trades: int = 50
    growth_min_positive_fold_ratio: float = 0.65
    growth_min_bootstrap_probability: float = 0.58
    growth_max_daily_experiments: int = 25
    growth_search_queries: int = 4
    growth_event_horizon_bars: int = 8
    cross_asset_symbols: tuple[str, ...] = ("BTC/USDT", "ETH/USDT", "SOL/USDT")
    orderbook_levels: int = 50
    orderbook_impact_notional: float = 10000.0
    semantic_memory_features: int = 256
    incremental_refresh: bool = True
    efficiency_corr_threshold: float = 0.995
    growth_compute_budget: float = 12.0
    growth_task_top_k: int = 10
    experience_graph_max_rows: int = 5000
    online_learning_enabled: bool = True
    deep_evolution_enabled: bool = True
    causal_match_k: int = 5
    causal_exclusion_bars: int = 8
    causal_control_lookback_bars: int = 1500
    intrabar_barriers: bool = True
    regime_weight: float = 0.08
    uncertainty_penalty_mult: float = 2.0
    memory_weight: float = 0.16
    meta_weight: float = 0.18
    conviction_weight: float = 0.34
    edge_weight: float = 0.30
    xgb_estimators: int = 240
    lgbm_estimators: int = 240
    hist_max_iter: int = 260
    regime_n_init: int = 5
    external_feature_lag_bars: int = 1
    conformal_level: float = 0.90
    conformal_blend: float = 0.60
    signal_only_mode: bool = True
    signal_confidence_threshold: float = 0.82
    signal_probability_threshold: float = 0.72
    signal_min_expected_return: float = 0.003
    signal_meta_threshold: float = 0.62
    signal_min_score: float = 0.22
    signal_max_disagreement: float = 0.05
    signal_memory_min_neighbors: int = 16
    signal_memory_min_agreement: float = 0.70
    signal_graph_min_samples: int = 8
    signal_graph_min_win_rate: float = 0.62
    signal_analog_support_scale: int = 24
    signal_graph_support_scale: int = 16
    signal_rearm_below: float = 0.68
    objective_min_edge: float = 0.003
    objective_max_data_age_minutes: float = 30.0
    objective_duration_bonus: float = 0.04
    autonomous_research_window_bars: int = 8000
    master_tuning_cache_dir: str = "data/master_cache"
    mutation_max_features: int = 40
    short_borrow_bps_per_bar: float = 0.0
    require_short_borrow_cost: bool = True
    funding_rate_column: str = "funding_rate"
    funding_interval_hours: float = 8.0
    funding_bps_per_bar: float = 0.0
    require_funding_data_for_derivatives: bool = True
    backtest_market_type: str = "spot"
    memory_exclusion_bars: int = 12
    research_ledger_path: str = "data/research_ledger.json"
    live_portfolio_correlation_bars: int = 96
    live_max_pairwise_return_correlation: float = 0.80
    live_min_correlation_observations: int = 48
    force_daily_loss_exit: bool = True
    online_warmup_rows: int = 64
    universe_manifest: str = "data/real_universe/manifest.json"
    max_parallel_downloads: int = 10
    broad_crypto_symbol_cap: int = 500
    intraday_research_top_n: int = 30
    final_holdout_frac: float = 0.15
    master_audit_folds: int = 18
    master_optimization_folds: int = 6
    historical_sources: tuple[str, ...] = ("binance", "fred", "sec", "cftc", "treasury", "alpha_vantage")
    live_symbols: tuple[str, ...] = (\n        "BTC/USDT", "ETH/USDT", "BNB/USDT", "SOL/USDT", "XRP/USDT",\n        "ADA/USDT", "DOGE/USDT", "AVAX/USDT", "LINK/USDT", "DOT/USDT",\n        "LTC/USDT", "BCH/USDT", "ATOM/USDT", "UNI/USDT", "ETC/USDT",\n    )


def load_settings(path: str | Path = ROOT / "config.yaml") -> Settings:
    raw = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
    sections = ("data", "model", "risk", "research", "execution", "app", "autonomy", "growth", "real_data")
    top_level = {key: value for key, value in raw.items() if key not in sections}
    section_values = {key: value for section in sections for key, value in (raw.get(section, {}) or {}).items()}
    d = {**top_level, **section_values}
    return Settings(
        exchange=str(d.get("exchange", "binance")),
        cache_dir=str(d.get("cache_dir", "data")),
        log_level=str(d.get("log_level", "INFO")),
        timezone=str(d.get("timezone", "UTC")),
        symbol=os.getenv("SYMBOL", d.get("symbol", "BTC/USDT")),
        timeframe=os.getenv("TIMEFRAME", d.get("timeframe", "15m")),
        research_timeframe=str(d.get("research_timeframe", d.get("timeframe", "15m"))),
        broad_timeframe=str(d.get("broad_timeframe", "1d")),
        lookback_bars=int(os.getenv("LOOKBACK_BARS", d.get("lookback_bars", 8000))),
        horizon_bars=int(d.get("horizon_bars", 8)),
        min_train_rows=int(d.get("min_train_rows", 1500)),
        retrain_every_bars=int(d.get("retrain_every_bars", 96)),
        probability_threshold=float(d.get("probability_threshold", 0.57)),
        min_expected_return=float(os.getenv("MIN_EDGE", d.get("min_expected_return", 0.0015))),
        min_edge_after_cost_bps=float(d.get("min_edge_after_cost_bps", 5.0)),
        decision_threshold=float(d.get("decision_threshold", 0.16)),
        meta_threshold=float(d.get("meta_threshold", 0.53)),
        pt_atr=float(d.get("pt_atr", 1.6)),
        sl_atr=float(d.get("sl_atr", 1.0)),
        memory_k=int(d.get("memory_k", 32)),
        memory_information_weighted=_bool(d.get("memory_information_weighted")),
        max_holding_bars=int(d.get("max_holding_bars", 96)),
        trade_window_enabled=_bool(d.get("trade_window_enabled", True)),
        trade_window_required_for_signal=_bool(d.get("trade_window_required_for_signal", True)),
        trade_window_min_confidence=float(d.get("trade_window_min_confidence", 0.80)),
        trade_window_min_expected_return=float(d.get("trade_window_min_expected_return", 0.0015)),
        trade_window_require_base_agreement=_bool(d.get("trade_window_require_base_agreement", True)),
        trade_window_min_hours=float(d.get("trade_window_min_hours", 3.0)),
        trade_window_max_hours=float(d.get("trade_window_max_hours", 24.0)),
        trade_window_preferred_min_hours=float(d.get("trade_window_preferred_min_hours", 3.0)),
        trade_window_preferred_max_hours=float(d.get("trade_window_preferred_max_hours", 4.0)),
        trade_window_preference_weight=float(d.get("trade_window_preference_weight", 0.10)),
        trade_window_pt_atr=float(d.get("trade_window_pt_atr", 1.25)),
        trade_window_sl_atr=float(d.get("trade_window_sl_atr", 0.90)),
        trade_window_min_net_return=float(d.get("trade_window_min_net_return", 0.0005)),
        trade_window_target_precision=float(d.get("trade_window_target_precision", 0.80)),
        trade_window_min_oos_trades=int(d.get("trade_window_min_oos_trades", 25)),
        trade_window_min_holdout_trades=int(d.get("trade_window_min_holdout_trades", 12)),
        trade_window_min_holdout_wilson=float(d.get("trade_window_min_holdout_wilson", 0.60)),
        trade_window_min_oos_wilson=float(d.get("trade_window_min_oos_wilson", 0.60)),
        trade_window_require_positive_holdout_backtest=_bool(d.get("trade_window_require_positive_holdout_backtest", True)),
        base_require_positive_holdout_return=_bool(d.get("base_require_positive_holdout_return", True)),
        base_min_holdout_trades=int(d.get("base_min_holdout_trades", 20)),
        base_min_holdout_profit_factor=float(d.get("base_min_holdout_profit_factor", 1.0)),
        base_max_holdout_drawdown=float(d.get("base_max_holdout_drawdown", -0.25)),
        base_min_holdout_utility=float(d.get("base_min_holdout_utility", 0.0)),
        require_deployment_manifest_for_signal=_bool(d.get("require_deployment_manifest_for_signal", True)),
        trade_window_max_holdout_drawdown=float(d.get("trade_window_max_holdout_drawdown", -0.25)),
        trade_window_min_holdout_utility=float(d.get("trade_window_min_holdout_utility", 0.0)),
        trade_window_holdout_frac=float(d.get("trade_window_holdout_frac", d.get("final_holdout_frac", 0.15))),
        trade_window_model_path=str(d.get("trade_window_model_path", "models/champion/trade_window_specialist.joblib")),
        trade_window_xgb_estimators=int(d.get("trade_window_xgb_estimators", 180)),
        trade_window_lgbm_estimators=int(d.get("trade_window_lgbm_estimators", 180)),
        trade_window_hist_max_iter=int(d.get("trade_window_hist_max_iter", 220)),
        initial_cash=float(os.getenv("INITIAL_CASH", d.get("initial_cash", 10000))),
        risk_per_trade=float(os.getenv("RISK_PER_TRADE", d.get("risk_per_trade", 0.005))),
        max_position_pct=float(os.getenv("MAX_POSITION_PCT", d.get("max_position_pct", 0.25))),
        max_daily_loss_pct=float(d.get("max_daily_loss_pct", 0.02)),
        stop_atr_mult=float(d.get("stop_atr_mult", 1.8)),
        take_profit_rr=float(d.get("take_profit_rr", 2.2)),
        fee_bps=float(os.getenv("FEE_BPS", d.get("fee_bps", 7))),
        slippage_bps=float(os.getenv("SLIPPAGE_BPS", d.get("slippage_bps", 5))),
        impact_bps_per_sqrt=float(d.get("impact_bps_per_sqrt", 1.5)),
        max_participation_pct=float(d.get("max_participation_pct", 0.10)),
        paper_only=_bool(os.getenv("PAPER_ONLY", d.get("paper_only", True))),
        sandbox=_bool(os.getenv("SANDBOX", d.get("sandbox", True))),
        poll_seconds=int(d.get("poll_seconds", 60)),
        live_lookback_bars=int(d.get("live_lookback_bars", 600)),
        live_max_symbols=int(d.get("live_max_symbols", 0)),
        live_market_types=tuple(d.get("live_market_types", ("spot", "swap", "future", "margin", "option")) or ("spot", "swap", "future", "margin")),
        live_default_refresh_seconds=int(d.get("live_default_refresh_seconds", 60)),
        live_scan_workers=max(1, min(8, int(d.get("live_scan_workers", 6)))),
        seed=int(d.get("seed", 42)),
        walk_forward_train_bars=int(d.get("walk_forward_train_bars", 3000)),
        walk_forward_test_bars=int(d.get("walk_forward_test_bars", 500)),
        walk_forward_step=int(d.get("step_bars", d.get("walk_forward_step", 250))),
        validation_purge_bars=int(d.get("validation_purge_bars", 12)),
        population_size=int(d.get("population_size", 500)),
        generations=int(d.get("generations", 30)),
        min_trades_promotion=int(d.get("min_trades_promotion", 20)),
        max_promotion_drawdown=float(d.get("max_promotion_drawdown", -0.20)),
        autonomous_enabled=_bool(d.get("autonomous_enabled", True)),
        autonomous_query=str(d.get("autonomous_query", "latest Bitcoin crypto markets macro catalysts regulation ETF flows volatility")),
        autonomous_interval_seconds=int(d.get("autonomous_interval_seconds", 900)),
        intelligence_db=str(d.get("intelligence_db", "data/intelligence.sqlite")),
        memory_db=str(d.get("memory_db", "data/memory.sqlite")),
        external_deep_search=_bool(d.get("external_deep_search", True)),
        external_providers=tuple(d.get("external_providers", ("exa", "tavily")) or ()),
        external_search_ttl_seconds=int(d.get("external_search_ttl_seconds", 1800)),
        fred_series=tuple(d.get("fred_series", ("DFF", "DGS10", "DTWEXBGS", "VIXCLS")) or ()),
        sec_ciks=tuple(d.get("sec_ciks", ()) or ()),
        growth_enabled=_bool(d.get("growth_enabled", True)),
        growth_min_folds=int(d.get("growth_min_folds", 4)),
        growth_min_trades=int(d.get("growth_min_trades", 50)),
        growth_min_positive_fold_ratio=float(d.get("growth_min_positive_fold_ratio", 0.65)),
        growth_min_bootstrap_probability=float(d.get("growth_min_bootstrap_probability", 0.58)),
        growth_max_daily_experiments=int(d.get("growth_max_daily_experiments", 25)),
        growth_search_queries=int(d.get("growth_search_queries", 4)),
        growth_event_horizon_bars=int(d.get("growth_event_horizon_bars", d.get("horizon_bars", 8))),
        cross_asset_symbols=tuple(d.get("cross_asset_symbols", ("BTC/USDT", "ETH/USDT", "SOL/USDT")) or ()),
        orderbook_levels=int(d.get("orderbook_levels", 50)),
        orderbook_impact_notional=float(d.get("orderbook_impact_notional", 10000.0)),
        semantic_memory_features=int(d.get("semantic_memory_features", 256)),
        incremental_refresh=_bool(d.get("incremental_refresh", True)),
        efficiency_corr_threshold=float(d.get("efficiency_corr_threshold", 0.995)),
        growth_compute_budget=float(d.get("growth_compute_budget", 12.0)),
        growth_task_top_k=int(d.get("growth_task_top_k", 10)),
        experience_graph_max_rows=int(d.get("experience_graph_max_rows", 5000)),
        online_learning_enabled=_bool(d.get("online_learning_enabled", True)),
        deep_evolution_enabled=_bool(d.get("deep_evolution_enabled", True)),
        causal_match_k=int(d.get("causal_match_k", 5)),
        causal_exclusion_bars=int(d.get("causal_exclusion_bars", d.get("horizon_bars", 8))),
        causal_control_lookback_bars=int(d.get("causal_control_lookback_bars", 1500)),
        intrabar_barriers=_bool(d.get("intrabar_barriers", True)),
        regime_weight=float(d.get("regime_weight", 0.08)),
        uncertainty_penalty_mult=float(d.get("uncertainty_penalty_mult", 2.0)),
        memory_weight=float(d.get("memory_weight", 0.16)),
        meta_weight=float(d.get("meta_weight", 0.18)),
        conviction_weight=float(d.get("conviction_weight", 0.34)),
        edge_weight=float(d.get("edge_weight", 0.30)),
        xgb_estimators=int(d.get("xgb_estimators", 240)),
        lgbm_estimators=int(d.get("lgbm_estimators", 240)),
        hist_max_iter=int(d.get("hist_max_iter", 260)),
        regime_n_init=int(d.get("regime_n_init", 5)),
        external_feature_lag_bars=int(d.get("external_feature_lag_bars", 1)),
        conformal_level=float(d.get("conformal_level", 0.90)),
        conformal_blend=float(d.get("conformal_blend", 0.60)),
        signal_only_mode=_bool(d.get("signal_only_mode", True)),
        signal_confidence_threshold=float(d.get("signal_confidence_threshold", 0.82)),
        signal_probability_threshold=float(d.get("signal_probability_threshold", 0.72)),
        signal_min_expected_return=float(d.get("signal_min_expected_return", 0.003)),
        signal_meta_threshold=float(d.get("signal_meta_threshold", 0.62)),
        signal_min_score=float(d.get("signal_min_score", 0.22)),
        signal_max_disagreement=float(d.get("signal_max_disagreement", 0.05)),
        signal_memory_min_neighbors=int(d.get("signal_memory_min_neighbors", 16)),
        signal_memory_min_agreement=float(d.get("signal_memory_min_agreement", 0.70)),
        signal_graph_min_samples=int(d.get("signal_graph_min_samples", 8)),
        signal_graph_min_win_rate=float(d.get("signal_graph_min_win_rate", 0.62)),
        signal_analog_support_scale=int(d.get("signal_analog_support_scale", 24)),
        signal_graph_support_scale=int(d.get("signal_graph_support_scale", 16)),
        signal_rearm_below=float(d.get("signal_rearm_below", 0.68)),
        objective_min_edge=float(d.get("objective_min_edge", 0.003)),
        objective_max_data_age_minutes=float(d.get("objective_max_data_age_minutes", 30.0)),
        objective_duration_bonus=float(d.get("objective_duration_bonus", 0.04)),
        autonomous_research_window_bars=int(d.get("autonomous_research_window_bars", 8000)),
        master_tuning_cache_dir=str(d.get("master_tuning_cache_dir", "data/master_cache")),
        mutation_max_features=int(d.get("mutation_max_features", 40)),
        short_borrow_bps_per_bar=float(d.get("short_borrow_bps_per_bar", 0.0)),
        require_short_borrow_cost=_bool(d.get("require_short_borrow_cost", True)),
        funding_rate_column=str(d.get("funding_rate_column", "funding_rate")),
        funding_interval_hours=float(d.get("funding_interval_hours", 8.0)),
        funding_bps_per_bar=float(d.get("funding_bps_per_bar", 0.0)),
        require_funding_data_for_derivatives=_bool(d.get("require_funding_data_for_derivatives", True)),
        backtest_market_type=str(d.get("backtest_market_type", "spot")),
        memory_exclusion_bars=int(d.get("memory_exclusion_bars", max(1, int(d.get("validation_purge_bars", 12))))),
        research_ledger_path=str(d.get("research_ledger_path", "data/research_ledger.json")),
        live_portfolio_correlation_bars=int(d.get("live_portfolio_correlation_bars", 96)),
        live_max_pairwise_return_correlation=float(d.get("live_max_pairwise_return_correlation", 0.80)),
        live_min_correlation_observations=int(d.get("live_min_correlation_observations", 48)),
        force_daily_loss_exit=_bool(d.get("force_daily_loss_exit", True)),
        online_warmup_rows=int(d.get("online_warmup_rows", 64)),
        universe_manifest=str(d.get("universe_manifest", "data/real_universe/manifest.json")),
        max_parallel_downloads=int(d.get("max_parallel_downloads", 6)),
        broad_crypto_symbol_cap=int(d.get("broad_crypto_symbol_cap", 250)),
        intraday_research_top_n=int(d.get("intraday_research_top_n", 10)),
        final_holdout_frac=float(d.get("final_holdout_frac", 0.15)),
        master_audit_folds=int(d.get("master_audit_folds", 18)),
        master_optimization_folds=int(d.get("master_optimization_folds", 6)),
        historical_sources=tuple(d.get("historical_sources", ("binance", "fred", "sec", "cftc", "treasury", "alpha_vantage")) or ()),
        live_symbols=tuple(d.get("live_symbols", ("BTC/USDT", "ETH/USDT", "SOL/USDT")) or ()),
    )